/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lemon_hellojni_MainActivity */

#ifndef _Included_lemon_hellojni_MainActivity
#define _Included_lemon_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lemon_hellojni_MainActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lemon_hellojni_MainActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
